### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by soulfoodz** [jamztang/ObjectiveSpring#1]
Using xcode 6.3, I get 14 errors when I try to run. All are Swift Compiler Errors. Am I missing something?

**Comment by ilesmana** [comment]
me too, please update on xcode 6.3

**Comment by soulfoodz** [comment]
To fix this:
1. copy the Spring framework to a safe place. 
2. Delete Spring from the project
3. Create a Swift header file. (name doesn't matter. It's never going to be used. It's just needed for next step)
4. After saving it, you should see a pop-up from xcode asking if you want it to create a bridging header file for you.
5. Select "Yes". You DO want a bridging header created for you.
6. Add Spring back to the project.
7. Run. It should work.

**Comment by mithralaya** [comment]
this project doesnt work.. :(

**Comment by jamztang** [comment]
Thanks guys. The embedded Spring framework wasn't updated, what I did is just remove the Spring folder from the project and drag in a fresh copy of the latest Spring, now it's fixed.
