### ISSUE TITLE
Get Animation to AutoStart in Code

### ISSUE THREAD

**Issue by connman21** [jamztang/ObjectiveSpring#4]
@jamztang - What would it look like to have a UIButton animation being triggered in viewDidLoad?

MY PROBLEM: My view is reached via performSegueWithIdentifier, so I am not able to AutoStart my Spring animation. I want to set all my variables for the animations in my Storyboard and just trigger the animations programmatically in viewDidLoad.

Thanks for your help -- I LOVE how amazing your code is to allow great animations from the Storyboard... its so awesome for designers like me who aren't hard-core developers.

**Comment by jamztang** [comment]
I just updated the README :)

**Comment by connman21** [comment]
@jamtang - What about animating a button showing up on the Storyboard at all? 
So, not an action but just its arrival ("slideUp" for example) being triggered in that code?
